-- Auto-generated command list for GobbieBars Buttons
return {
CW = {
	{ text = "!artifacts", command = "!artifacts", tooltip = "SCNMs award players pieces of Summit Armor and materials\nfor augmenting and upgrading that armor." },
	{ text = "!box ITEM_NAME", command = "!box ITEM_NAME", tooltip = "Anywhere in the world: Check your stock for the given item\nWithin 5 yalms of an Ephemeral Box: Withdraw the item via a menu\nFor example: !box Wool Cloth" },
	{ text = "!box ITEM_ID", command = "!box ITEM_ID", tooltip = "Anywhere in the world: Check your stock for the given item\nWithin 5 yalms of an Ephemeral Box: Withdraw the item via a menu\nFor example: !box 4401" },
	{ text = "!box QUANTITY ITEM_NAME", command = "!box QUANTITY ITEM_NAME", tooltip = "Anywhere in the world: Check your stock for the given item\nWithin 5 yalms of an Ephemeral Box: Withdraw the item via a menu\n!box 12 Wool Cloth" },
	{ text = "!box QUANTITY ITEM_ID", command = "!box QUANTITY ITEM_ID", tooltip = "Anywhere in the world: Check your stock for the given item\nWithin 5 yalms of an Ephemeral Box: Withdraw the item via a menu\n!box 12 4401" },
	{ text = "!box ammo", command = "!box ammo", tooltip = "Within 5 yalms of an Ephemeral Box:\nWithdraw ammo as quivers, cases & boxes." },
	{ text = "!box cluster", command = "!box cluster", tooltip = "Within 5 yalms of an Ephemeral Box:\nWithdraw crystals as clusters." },
	{ text = "!box store", command = "!box store", tooltip = "Within 5 yalms of an Ephemeral Box:\nInstantly store every storable item in their inventory.\n\nCommand to customize the behavior of this command:\nebox_store_food true or false\nebox_store_ammo true/false\nebox_store_tools true or false\nebox_store_potion true or false\nebox_store_pet true or false" },
	{ text = "!config", command = "!config", tooltip = "Configure server-side quality-of-life options:\nebox_store_food true/false\nebox_store_ammo true/false\nebox_store_tools true/false\nebox_store_potion true/false\nebox_store_pet true/false\nemilia_signet true/false (auto Signet upon teleporting with Emilia)\nno_equip_messages true/false (show/hide equip bonuses for traits)\nprestige_hidden true/false (show or hide your Prestige stars)\nventure_list_full true/false (true=show all, false= exp only)\nwarp_scrolls true/false (auto buy Warp Scroll for 10 CP upon teleporting with Emilia, Domenic or Runic Portal)" },
	{ text = "!currency", command = "!currency", tooltip = "Shows Dynamis currencies, Alexandrite, H-P Bayld, and Incursion currencies with storage locations." },
	{ text = "!dailies", command = "!dailies", tooltip = "Displays current daily objectives." },
	{ text = "!dailykills", command = "!dailykills", tooltip = "Tracks progress for Murdox objectives." },
	{ text = "!dawnunstuck", command = "!dawnunstuck", tooltip = "Release character from stuck mission events" },
	{ text = "!delexp", command = "!delexp", tooltip = "Removes dedication EXP buff" },
	{ text = "!essences", command = "!essences", tooltip = "Verify Dynamis 2.0 completion" },
	{ text = "!help", command = "!help", tooltip = "Display all available commands" },
	{ text = "!keys", command = "!keys", tooltip = "Display stored chest and coffer keys" },
	{ text = "!lsstats", command = "!lsstats", tooltip = "Display Linkshell contribution rankings" },
	{ text = "!maat", command = "!maat", tooltip = "Display Maat victory jobs" },
	{ text = "!pf", command = "!pf", tooltip = "Party Finder listing" },
	{ text = "!points", command = "!points", tooltip = "Includes Arena Points, Gobbie Grandeur Points, Helper Points." },
	{ text = "!pops", command = "!pops", tooltip = "Display available NM pop conditions" },
	{ text = "!prestige", command = "!prestige", tooltip = "Display active Prestige bonuses" },
	{ text = "!quest", command = "!quest", tooltip = "Display CatsEye custom quest progress" },
	{ text = "!re", command = "!re", tooltip = "Refresh party and zone state" },
	{ text = "!rubyweather", command = "!rubyweather", tooltip = "Display unlocked SMN weathers" },
	{ text = "!skills", command = "!skills", tooltip = "Displays special NPC rep" },
	{ text = "!skipfloor", command = "!skipfloor", tooltip = "Skip floors in Nyzul Isle" },
	{ text = "!rifts", command = "!rifts", tooltip = "Display active Rift locations" },
	{ text = "!summit", command = "!summit", tooltip = "Toggles LS contribution; 30-minute cooldown." },
	{ text = "!summitcalc", command = "!summitcalc", tooltip = "Calculate adjusted Summit points" },
	{ text = "!summitnotify", command = "!summitnotify", tooltip = "Toggle Summit notifications" },
	{ text = "!summitreward", command = "!summitreward", tooltip = "Set Summit reward type" },
	{ text = "!summitcalc POINTS_AMOUNT", command = "!summitcalc POINTS_AMOUNT", tooltip = "Your contribution towards the LS,\nwhere POINTS_AMOUNT is the amount of points you received" },
	{ text = "!summitreward gil", command = "!summitreward gil", tooltip = "The linkshell owner can choose whether their linkshell receives Gil or Wyrm Gold" },
	{ text = "!summitreward wyrmgold", command = "!summitreward wyrmgold", tooltip = "The linkshell owner can choose\nwhether their linkshell receives Gil or Wyrm Gold" },
	{ text = "!trials", command = "!trials", tooltip = "View novice trial progress" },
	{ text = "!vault", command = "!vault", tooltip = "Access Mog Vault" },
	{ text = "!venture", command = "!venture", tooltip = "Enable or disable Ventures" },
	{ text = "!ventures", command = "!ventures", tooltip = "Lists all of the various Ventures objectives for the day." },
	{ text = "!ventures dynamis", command = "!ventures dynamis", tooltip = "Lists the dynamis Ventures objectives for the day.\nCustomize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!ventures exp", command = "!ventures exp", tooltip = "Lists the exp Ventures objectives for the day.\nCustomize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!ventures fishing", command = "!ventures fishing", tooltip = "Lists the fishing Ventures objectives for the day.\nCustomize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!ventures helm", command = "!ventures helm", tooltip = "Lists the helm Ventures objectives for the day.\nCustomize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!hunter", command = "!hunter", tooltip = "Display your current weekly hunt objective." },
	{ text = "!incursion", command = "!incursion", tooltip = "Shows occupied zones and remaining time." },
	{ text = "!pass", command = "!pass", tooltip = "Displays garrison pop items stored with Picklox." },
	{ text = "!scroll SCROLL_NAME", command = "!scroll SCROLL_NAME", tooltip = "Verifies storage in Ephemeral Box or Gramateus." },
	{ text = "!newadventurer", command = "!newadventurer", tooltip = "Clears the ? icon from new characters." },
	{ text = "!wspoints main", command = "!wspoints main", tooltip = "Total WS point gained for your main hand" },
	{ text = "!wspoints sub", command = "!wspoints sub", tooltip = "Total WS point gained for your sub" },
	{ text = "!wspoints ranged", command = "!wspoints ranged", tooltip = "Total WS point gained for your ranged" },
	},
ACE = {
	{ text = "!artifacts", command = "!artifacts", tooltip = "SCNMs award players pieces of Summit Armor and materials for augmenting and upgrading that armor." },
	{ text = "!chef", command = "!chef", tooltip = "Available foods:\nAntacid (8,000G)\nMeat Jerky (2,000G)\nMeat Mithkabob (5,000G)\nCoeurl Sub (7,000G)\nBoiled Crab (2,000G)\nFish Mithkabob (5,000G)\nJack-o'-Lantern (2,000G)\nTuna Sushi (8,000G)\nDorado Sushi (8,000G)\nApple Pie (2,000G)\nMelon Pie (2,000G)\nCream Puff (7,000G)\nOrange Juice (2,000G)\nMelon Juice (5,000G)\nYagudo Drink (7,000G)" },
	{ text = "!config", command = "!config", tooltip = "Configure server-side quality-of-life options" },
	{ text = "!currency", command = "!currency", tooltip = "Shows Dynamis currencies;\nAlexandrite, H-P Bayld, and Incursion currencies with storage locations." },
	{ text = "!dailies", command = "!dailies", tooltip = "Displays current daily objectives." },
	{ text = "!dailykills", command = "!dailykills", tooltip = "Tracks progress for Murdox objectives." },
	{ text = "!dawnunstuck", command = "!dawnunstuck", tooltip = "Intended for CoP 8-4 Dawn, may resolve other mission lockups." },
	{ text = "!delexp", command = "!delexp", tooltip = "Immediately clears the dedication effect." },
	{ text = "!essences", command = "!essences", tooltip = "Shows obtained Dynamis 2.0 victories." },
	{ text = "!help", command = "!help", tooltip = "Lists commands available to the character." },
	{ text = "!lsstats", command = "!lsstats", tooltip = "Shows top contributors for Summit of the Stars." },
	{ text = "!maat", command = "!maat", tooltip = "Shows which jobs were used to defeat Maat." },
	{ text = "!pf", command = "!pf", tooltip = "Displays players currently seeking via Party Finder." },
	{ text = "!points", command = "!points", tooltip = "Includes Obsidian Fragments, Escha Beads, Dynamis RP, DKP, and Ventures." },
	{ text = "!pops", command = "!pops", tooltip = "Covers Domain Invasion, Goblin Brew, Sky 2.0, and Guild NMs." },
	{ text = "!prestige", command = "!prestige", tooltip = "Shows currently enabled Prestige effects." },
	{ text = "!quest", command = "!quest", tooltip = "Shows progress across server-specific quests." },
	{ text = "!re", command = "!re", tooltip = "Fixes party visibility or zone sync issues." },
	{ text = "!rubyweather", command = "!rubyweather", tooltip = "Shows unlocked weathers for “I Can Hear a Rainbow”." },
	{ text = "!sanction", command = "!sanction", tooltip = "Can be used anywhere in the game.        " },
	{ text = "!sigil", command = "!sigil", tooltip = "Can be used anywhere in the game." },
	{ text = "!signet", command = "!signet", tooltip = "Can be used anywhere in the game." },
	{ text = "!skills", command = "!skills", tooltip = "Includes custom skills such as Garbagio." },
	{ text = "!skipfloor", command = "!skipfloor", tooltip = "Available every 30 minutes; lockout applies to the full party." },
	{ text = "!rifts", command = "!rifts", tooltip = "Shows when and where Rifts are open." },
	{ text = "!summitcalc", command = "!summitcalc", tooltip = "Shows contribution breakdown for a given point amount." },
	{ text = "!summitnotify", command = "!summitnotify", tooltip = "Enables or disables zoning notifications." },
	{ text = "!summitreward", command = "!summitreward", tooltip = "LS owners choose between gil or Wyrm Gold rewards." },
	{ text = "!summitcalc POINTS_AMOUNT", command = "!summitcalc POINTS_AMOUNT", tooltip = "Your contribution towards the LS, where POINTS_AMOUNT is the amount of points you received" },
	{ text = "!trials", command = "!trials", tooltip = "Displays current novice trial completion." },
	{ text = "!vault", command = "!vault", tooltip = "Available in towns after completing the required quest." },
	{ text = "!venture", command = "!venture", tooltip = "Toggles Venture participation." },
	{ text = "!ventures exp", command = "!ventures exp", tooltip = "Customize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!ventures fishing", command = "!ventures fishing", tooltip = "Customize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!ventures helm", command = "!ventures helm", tooltip = "Customize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!wspoints main", command = "!wspoints main", tooltip = "Total WS point gained for your main hand" },
	{ text = "!wspoints sub", command = "!wspoints sub", tooltip = "Total WS point gained for your sub" },
	{ text = "!wspoints ranged", command = "!wspoints ranged", tooltip = "Total WS point gained for your ranged" },
	{ text = "!fatigue", command = "!fatigue", tooltip = "Shows remaining fishing actions for the day." },
	{ text = "!mog", command = "!mog", tooltip = "City-only usage." },
	{ text = "!newadventurer", command = "!newadventurer", tooltip = "Clears the ? icon from new characters." },
},
  WEW = {
	{ text = "!artifacts", command = "!artifacts", tooltip = "SCNMs award players pieces of Summit Armor and materials for augmenting and upgrading that armor." },
	{ text = "!chef", command = "!chef", tooltip = "Available foods:\nAntacid (8,000G)\nMeat Jerky (2,000G)\nMeat Mithkabob (5,000G)\nCoeurl Sub (7,000G)\nBoiled Crab (2,000G)\nFish Mithkabob (5,000G)\nJack-o'-Lantern (2,000G)\nTuna Sushi (8,000G)\nDorado Sushi (8,000G)\nApple Pie (2,000G)\nMelon Pie (2,000G)\nCream Puff (7,000G)\nOrange Juice (2,000G)\nMelon Juice (5,000G)\nYagudo Drink (7,000G)" },
	{ text = "!config", command = "!config", tooltip = "Configure server-side quality-of-life options" },
	{ text = "!currency", command = "!currency", tooltip = "Shows Dynamis currencies;\nAlexandrite, H-P Bayld, and Incursion currencies with storage locations." },
	{ text = "!dailies", command = "!dailies", tooltip = "Displays current daily objectives." },
	{ text = "!dailykills", command = "!dailykills", tooltip = "Tracks progress for Murdox objectives." },
	{ text = "!dawnunstuck", command = "!dawnunstuck", tooltip = "Intended for CoP 8-4 Dawn, may resolve other mission lockups." },
	{ text = "!delexp", command = "!delexp", tooltip = "Immediately clears the dedication effect." },
	{ text = "!essences", command = "!essences", tooltip = "Shows obtained Dynamis 2.0 victories." },
	{ text = "!help", command = "!help", tooltip = "Lists commands available to the character." },
	{ text = "!lsstats", command = "!lsstats", tooltip = "Shows top contributors for Summit of the Stars." },
	{ text = "!maat", command = "!maat", tooltip = "Shows which jobs were used to defeat Maat." },
	{ text = "!pf", command = "!pf", tooltip = "Displays players currently seeking via Party Finder." },
	{ text = "!points", command = "!points", tooltip = "Includes Obsidian Fragments, Escha Beads, Dynamis RP, DKP, and Ventures." },
	{ text = "!pops", command = "!pops", tooltip = "Covers Domain Invasion, Goblin Brew, Sky 2.0, and Guild NMs." },
	{ text = "!prestige", command = "!prestige", tooltip = "Shows currently enabled Prestige effects." },
	{ text = "!quest", command = "!quest", tooltip = "Shows progress across server-specific quests." },
	{ text = "!re", command = "!re", tooltip = "Fixes party visibility or zone sync issues." },
	{ text = "!rubyweather", command = "!rubyweather", tooltip = "Shows unlocked weathers for “I Can Hear a Rainbow”." },
	{ text = "!skills", command = "!skills", tooltip = "Includes custom skills such as Garbagio." },
	{ text = "!skipfloor", command = "!skipfloor", tooltip = "Available every 30 minutes; lockout applies to the full party." },
	{ text = "!rifts", command = "!rifts", tooltip = "Shows when and where Rifts are open." },
	{ text = "!summitcalc", command = "!summitcalc", tooltip = "Shows contribution breakdown for a given point amount." },
	{ text = "!summitnotify", command = "!summitnotify", tooltip = "Enables or disables zoning notifications." },
	{ text = "!summitreward", command = "!summitreward", tooltip = "LS owners choose between gil or Wyrm Gold rewards." },
	{ text = "!summitcalc POINTS_AMOUNT", command = "!summitcalc POINTS_AMOUNT", tooltip = "Your contribution towards the LS,\nwhere POINTS_AMOUNT is the amount of points you received" },
	{ text = "!trials", command = "!trials", tooltip = "Displays current novice trial completion." },
	{ text = "!vault", command = "!vault", tooltip = "Available in towns after completing the required quest." },
	{ text = "!venture", command = "!venture", tooltip = "Toggles Venture participation." },
	{ text = "!ventures", command = "!ventures", tooltip = "Categories: dynamis, exp, fishing, helm." },
	{ text = "!ventures dynamis", command = "!ventures dynamis ", tooltip = "Customize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!ventures exp", command = "!ventures exp", tooltip = "Customize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!ventures fishing", command = "!ventures fishing", tooltip = "Customize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!ventures helm", command = "!ventures helm", tooltip = "Customize the behavior of this commandwith venture_list_full true or false" },
	{ text = "!fatigue", command = "!fatigue", tooltip = "Shows remaining fishing actions for the day." },
	{ text = "!mog", command = "!mog", tooltip = "City-only usage." },
	{ text = "!newadventurer", command = "!newadventurer", tooltip = "Clears the ? icon from new characters." },
	{ text = "!wspoints main", command = "!wspoints main", tooltip = "Total WS point gained for your main hand" },
	{ text = "!wspoints sub", command = "!wspoints sub", tooltip = "Total WS point gained for your sub" },
	{ text = "!wspoints ranged", command = "!wspoints ranged", tooltip = "Total WS point gained for your ranged" },
  },
}
